### PR TITLE
Add buttons back to the new UI

### PR DESCRIPTION
**Pull request by Terrails**
This is a fix for #10. The buttons are added right of the zoom and orientation elements like this:
comicfuzexample

### CODE REVIEW

**Comment by CircleLiu** [comment]
Thanks for helping.

For now, I found that manga uses the new reader while books and magazines still use the old-style reader.
This fix will cause the download button in books and magazines to disappear.

**Comment by Terrails** [comment]
Ah, I'll get a fix up for that then

**Comment by Terrails** [comment]
If there is anything else that needs to be changed, do tell me!

**Review by CircleLiu — APPROVED** [review]
LGTM.
Thank you for contributing!

**Pull request merged**
